services:
  notification-service:
    image: ghcr.io/${IMAGE_NAME}:latest
    container_name: notification-service-reshala
    ports:
      - "8182:8182"
    environment:
      - SERVER_PORT=8182
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_ENABLED=false

      # RabbitMQ Configuration
      - RABBIT_HOST=${RMQ_HOST}
      - RABBIT_PORT=${RMQ_PORT}
      - RABBIT_USERNAME=${RMQ_USERNAME}
      - RABBIT_PASSWORD=${RMQ_PASSWORD}
      - RABBIT_VHOST=${RMQ_VHOST}

      # Mail Configuration
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${RESEND_API_KEY}

    networks:
      - reshala-net
    restart: unless-stopped

networks:
  reshala-net:
    external: true