spring.application.name=notification-service

spring.cloud.config.enabled=false

server.port=8183

//||--RabbitMQ--||
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rmuser
spring.rabbitmq.password=rmpassword
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000ms
spring.rabbitmq.template.retry.max-attempts=3

//||--Eureka--||
eureka.client.service-url.defaultZone=http://eureka-user:zvBGTYdMUJV7mpRs35YA@localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

//||--MailSettings--||
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=a9f3052b45461a
spring.mail.password=ae4e25c063dcb8
spring.mail.properties.mail.smtp.localhost=localhost
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true